let target = document.getElementById("myDiv");
target.style.backgroundColor = "yellow";
target.style.margin = "20px";
target.style.padding = "10px";
target.style.fontSize = "18px";
target.style.fontWeight = "bold";
target.style.height = "200px";
target.style.width = "300px";
target.style.color = "blue";